export default {
  LOGIN: 'LOGIN',
  JOIN_FRIEND_CHAT: 'JOIN_FRIEND_CHAT',
  LEAVE_FRIEND_CHAT: 'LEAVE_FRIEND_CHAT',
  SEND_MESSAGE: 'SEND_MESSAGE',
  MESSAGE: 'MESSAGE',
  START_TYPING: 'START_TYPING',
  LEAVING_TYPING: 'LEAVING_TYPING',
  USER_IN_WRITING_STATUS: 'USER_IN_WRITING_STATUS',
  USER_IN_NOT_WRITING_STATUS: 'USER_IN_NOT_WRITING_STATUS',
  ACTIVE_USERS: 'ACTIVE_USERS'
};
