export default {
  LOGIN: 'LOGIN',
  JOIN_FRIEND_CHAT: 'JOIN_FRIEND_CHAT',
  LEAVE_FRIEND_CHAT: 'LEAVE_FRIEND_CHAT',
  SEND_MESSAGE: 'SEND_MESSAGE',
  MESSAGE: 'MESSAGE',
  START_TYPING: 'START_TYPING',
  LEAVING_TYPING: 'LEAVING_TYPING'
};
