export default {
  DISCONNECT: 'disconnect',
  LOGIN: 'LOGIN',
  JOIN_FRIEND_CHAT: 'JOIN_FRIEND_CHAT',
  LEAVE_FRIEND_CHAT: 'LEAVE_FRIEND_CHAT',
  START_TYPING: 'START_TYPING',
  LEAVING_TYPING: 'LEAVING_TYPING',
  SEND_MESSAGE: 'SEND_MESSAGE',
  ACTIVE_USERS: 'ACTIVE_USERS'
};
