export default {
  DISCONNECT: 'disconnect',
  LOGIN: 'LOGIN',
  JOIN_FRIEND_CHAT: 'JOIN_FRIEND_CHAT',
  MESSAGE: 'MESSAGE',
  LEAVE_FRIEND_CHAT: 'LEAVE_FRIEND_CHAT',
  START_TYPING: 'START_TYPING',
  LEAVING_TYPING: 'LEAVING_TYPING',
  SEND_MESSAGE: 'SEND_MESSAGE',
  ACTIVE_USERS: 'ACTIVE_USERS',
  LAST_MESSAGE_FROM_USER: 'LAST_MESSAGE_FROM_USER',
  USER_IN_WRITING_STATUS: 'USER_IN_WRITING_STATUS',
  USER_IN_NOT_WRITING_STATUS: 'USER_IN_NOT_WRITING_STATUS',
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  DELETE_ALL_MESSAGES_BY_USER: 'DELETE_ALL_MESSAGES_BY_USER'
};
